config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations'}
  resources :posts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[index show]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
    @post = Post.new
  end

  # GET /posts/1
  # GET /posts/1.json
  def show; end

  # GET /posts/new
  def new
    @post = current_user.posts.build
  end

  # GET /posts/1/edit
  def edit; end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to posts_path, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to posts_path, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:post)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ClubHouse</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" %>


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class = "navbar navbar-expand-lg navbar-dark" style="background-color: #7d0633;">

    <%= link_to 'ClubHouse', posts_path, class: "navbar-brand" %>     

      <div class = "navbar ml-auto">
        <ul class="navbar-nav">

          <% if user_signed_in? %>
            
            <li class="nav-item mr-3">
              <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "btn btn-warning btn-sm" %>
            </li>
          <% else %>
            <li class="nav-item mr-3">
              <%= link_to "Sign In", new_user_session_path, class: "btn btn-warning btn-sm" %>
            </li>
            <li class="nav-item mr-3">
            <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-warning btn-sm" %>
            </li>
            <% end %>

            
        </ul>
      </div>
    </nav>

    <div class = "container">
      <div class = "row">
        <div class = "col-md-6 offset-md-3">
          <% if flash[:notice] %>
            <p class="notice"><%= notice %></p>
          <% end %>
          
          <% if flash[:alert] %>
            <p class="alert"><%= alert %></p>
          <% end %>
        </div>
      </div>
    </div>

      <%= yield %>
    
  </body>
</html>

app/views/posts/_form.html.erb
<%= simple_form_for(@post) do |f| %>
  <%= f.error_notification %>

  <%= f.input :post, label: "Enter a Joke",
              input_html: { class: "textarea" },
              wrapper: false, label_html: { class: "label" },
              placeholder: "Write a joke.....", autofocus: true
  %>
  <br>
  <p class = "form-btn">
    <%= f.button :submit, class: "btn btn-warning btn-sm"%>
  </p>
<% end %>

app/views/posts/_posts.html.erb
<div class = "col-md-9">

    <% if user_signed_in? %>
        <h2 class = "text-center">Members Page</h2>
        <div class = "row">
            <div class = "col-md-2">
            <figure class="figure">
                <img src = "https://bulma.io/images/placeholders/64x64.png">                  
            </figure>
            </div>

            <div class = "col-md">
            <%= render 'form' %>
            </div>
        </div>

    <% else %>
        <h2 class = "text-center">Welcome to ClubHouse</h2>
        <p class = "text-center">
            <strong>Sign Up for membership: Create jokes and View other members  </strong>
        </p>

        <p class = "text-center">
            <strong>Sign In if already a member  </strong>
        </p>
    <% end %>


    <% @posts.each do |post| %>
        
        <div class = "row">
        <div class = "col-md-2">
            <% if user_signed_in? %>
                <figure class="figure">
                <img src = "https://bulma.io/images/placeholders/64x64.png">                  
                </figure>
            <% end %>
        </div>

        <div class = "col-md-10 card card-body bg-card">
            <% if user_signed_in? %><p>Create by: <%= post.user.name %></p><% end %>
            <%= post.post %>
        </div>
        
        </div>
        
        <% if user_signed_in? && current_user == post.user%>
        <div class = "row">
        <div class = "col-md-3 col-sm-3 ml-auto icons">
            <%= link_to post, class: "control" do %>
            <span class = 'icon'><i class = 'fa fa-link' aria-hidden = 'true'></i></span>
            <% end %>

            <%= link_to edit_post_path(post), class: "control" do %>
            <span class = 'icon'><i class = 'fa fa-pencil' aria-hidden = 'true'></i></span>
            <% end %>
            

            <%= link_to post, method: :delete, data: { confirm: 'Are you sure?' }, class: "control" do %>
            <span class = 'icon'><i class = 'fa fa-trash-o' aria-hidden = 'true'></i></span>
            <% end %>

            </div>
        </div>
        <% end %>
        
        <br>
    <% end %>
</div>

app/views/posts/_profile.html.erb
<div class = "col-md-3">
    <div class="card">
        <div class="card-header">
            <%= current_user.username %>
        </div>        
    </div>
</div>

app/views/posts/edit.html.erb
<div class = "container">
    <h1 class = "text-center">Editing Post</h1>

    <div class = "row">
        <div class = col-md>         

            <%= render 'form', post: @post %>

            <%= link_to 'Show', @post, class: "btn btn-warning" %> |
            <%= link_to 'Back', posts_path, class: "btn btn-warning" %>
        </div>
    </div>
</div>

app/views/posts/index.html.erb
<div class = "container">
  <div class = "row">
      <%= render "posts" %>
          
      <% if user_signed_in? %><%= render "profile" %><% end %>
  </div>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<div class = "container">
  <div class = "row">

    <strong class = "title text-center">Post:</strong>
    <div class = "col-md-6 card card-body bg-card">
      <%= @post.post %>
    </div>
  </div>
  <%= link_to 'Edit', edit_post_path(@post), class: "btn btn-warning" %> |
  <%= link_to 'Back', posts_path, class: "btn btn-warning" %>

</div>